import argparse
import json
import os
from glob import glob
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score
from predict import extract_features, FEATURE_NAMES

IMG_EXTS = ("*.jpg", "*.jpeg", "*.png", "*.webp", "*.bmp")


def collect(folder):
    paths = []
    for ext in IMG_EXTS:
        paths.extend(glob(os.path.join(folder, ext)))
        paths.extend(glob(os.path.join(folder, ext.upper())))
    return sorted(paths)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=".", help="Folder containing real/ and screen/")
    parser.add_argument("--out", default="recapture_model.json")
    args = parser.parse_args()

    real_paths = collect(os.path.join(args.data, "real"))
    screen_paths = collect(os.path.join(args.data, "screen"))

    if len(real_paths) < 5 or len(screen_paths) < 5:
        raise SystemExit("Need at least 5 images in both real/ and screen/. For final submission, collect 50+ each.")

    X, y = [], []
    for p in real_paths:
        X.append(extract_features(p)); y.append(0)
    for p in screen_paths:
        X.append(extract_features(p)); y.append(1)
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int32)

    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)
    clf = LogisticRegression(C=1.0, class_weight="balanced", max_iter=1000, random_state=42)

    if len(y) >= 20 and len(np.unique(y)) == 2:
        cv = StratifiedKFold(n_splits=min(5, min(np.bincount(y))), shuffle=True, random_state=42)
        scores = cross_val_score(clf, Xs, y, cv=cv, scoring="accuracy")
        print(f"Cross-validation accuracy: {scores.mean()*100:.2f}% (+/- {scores.std()*100:.2f}%)")

    clf.fit(Xs, y)
    model = {
        "feature_names": FEATURE_NAMES,
        "mean": scaler.mean_.tolist(),
        "scale": scaler.scale_.tolist(),
        "coef": clf.coef_[0].tolist(),
        "intercept": float(clf.intercept_[0]),
        "classes": ["real=0", "screen/recapture=1"],
        "note": "Generated by train.py. predict.py outputs probability of recapture."
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)
    print(f"Saved model to {args.out}")
    print(f"Training images: real={len(real_paths)}, screen={len(screen_paths)}")


if __name__ == "__main__":
    main()
